apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentsurvey-frontend
  namespace: studentsurvey
spec:
  replicas: 1
  selector:
    matchLabels: { app: studentsurvey-frontend }
  template:
    metadata:
      labels: { app: studentsurvey-frontend }
    spec:
      containers:
      - name: frontend
        image: docker.io/YOUR_DOCKERHUB_USERNAME/studentsurvey-frontend:__TAG__
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: API_BASE
          valueFrom: { configMapKeyRef: { name: frontend-config, key: API_BASE } }
        readinessProbe:
          httpGet: { path: /, port: 80 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /, port: 80 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "256Mi" }
