apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: studentsurvey-frontend
  namespace: studentsurvey
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: studentsurvey-frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target: { type: Utilization, averageUtilization: 70 }
